env:
  node: true
  commonjs: true
  es6: true
  jest: true
extends:
  - eslint:recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  no-trailing-spaces: "error"
  indent: ['error', 2]
  semi: ['error', 'always']
  no-console: 'warn'
  no-unused-vars: ['error', { argsIgnorePattern: '^_' }]
  object-curly-spacing: ['error', 'always']
  array-bracket-spacing: ['error', 'never']
  comma-dangle: ['error', 'never']
  eol-last: ['error', 'always']
  func-style: ['error', 'expression']
  no-multiple-empty-lines: ['error', { max: 1 }]
  no-useless-return: 'error'
  prefer-const: 'error'
  arrow-parens: ['error', 'as-needed']
  no-extra-parens: ['error', 'all']
